version: '3'
services:
  frontend:
    build: ./my-frontend
    ports:
      - "8080:8080"
  backend:
    build: ./my_backend_app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db-data:
